fixtures:
  repositories:
    "facts": "git://github.com/puppetlabs/puppetlabs-facts.git"
    "puppet_agent": "git://github.com/puppetlabs/puppetlabs-puppet_agent.git"
    "puppet_conf": "git://github.com/puppetlabs/puppetlabs-puppet_conf.git"
    "provision": "git://github.com/puppetlabs/provision.git"
  symlinks:
    "puppet_ciamohe": "#{source_dir}"
